### ISSUE TITLE
Problem finding exiftools

### ISSUE THREAD

**Issue by DrArn** [KIOS-Research/ImportPhotos#16]
Hi
I have some difficulties getting the plugin working in QGIS 3.2 under Linux Mint, I have exiftools installed on my system, but on startup I get the following errormessage in QGIS:

> ImportError: cannot import name 'QGis' 
> Traceback (most recent call last):
>   File "/home/arn/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 40, in 
> 	import exifread
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 674, in _import
> 	mod = _builtin_import(name, globals, locals, fromlist, level)
> ModuleNotFoundError: No module named 'exifread'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 337, in startPlugin
> 	plugins[packageName] = package.classFactory(iface)
>   File "/home/arn/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/init.py", line 32, in classFactory
> 	from .ImportPhotos import ImportPhotos
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 674, in _import
> 	mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/home/arn/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 48, in 
> 	from qgis.utils import QGis as Qgis  #  for QGIS 2
> ImportError: cannot import name 'QGis'
> 
> 
> Python-Version: 3.6.6 (default, Sep 12 2018, 18:26:19) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] 
> QGIS-Version: 3.2.3-Bonn Bonn, 9b17680 
> 
> Python-Pfad:
> /usr/share/qgis/python
> /home/arn/.local/share/QGIS/QGIS3/profiles/default/python
> /home/arn/.local/share/QGIS/QGIS3/profiles/default/python/plugins
> /usr/share/qgis/python/plugins
> /usr/lib/python36.zip
> /usr/lib/python3.6
> /usr/lib/python3.6/lib-dynload
> /usr/local/lib/python3.6/dist-packages
> /usr/lib/python3/dist-packages
> /home/arn/.local/share/QGIS/QGIS3/profiles/default/python

Any Ideas?
Greetings
Arn

**Comment by Mariosmsk** [comment]
@DrArn, try to run the following command on qgis python console:
import pip; pip.main(['install', 'exifread']); #10

**Comment by DrArn** [comment]
Thanks for the quick reply
I get:
```
import pip; pip.main(['install', 'exifread']);
Collecting exifread
  Downloading https://files.pythonhosted.org/packages/7b/cb/92b644626830115910cf2b36d3dfa600adbec86dff3207a7de3bfd6c6a60/ExifRead-2.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6mq5os0k/exifread/
1
```
I noticed that i have Python 2.7.15rc1 and Python 3.6.6, could this be a problem?

**Comment by Mariosmsk** [comment]
https://raw.githubusercontent.com/KIOS-Research/ImportPhotos/master/ImportPhotos.py
Replace the ImportPhotos.py here: C:\Users\USER.qgis2\python\plugins\ImportPhotos
Restart QGIS.
Let me know if its ok! Thanks for the issue! 
Marios

**Comment by DrArn** [comment]
I am running Linux Mint, so I changed the path accordingly:

**Comment by Mariosmsk** [comment]
/home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins

**Comment by DrArn** [comment]
@Mariosmsk Thanks, the path is the same, and the original problem seems to be fixed.
Also probably unrelated, but if I don't name the output file with a ".geojson" I also get an Error:

> Traceback (most recent call last):
>   File "/home/arn/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/ImportPhotos.py", line 515, in ok
>     self.extension_switch[self.file_extension.lower()])
> KeyError: ''

**Comment by chgeorgios** [comment]
Hi @DrArn,
We noticed that there are some issues to be fixed in our code in order to make the ImportPhotos tool to work with Linux. We are working on that and we will publish a new version soon.
Our apologies for any inconvenience.
We will let you know once we have the new version ready.
