### PR TITLE
Fixed relative path handling in PhotoWindow and ImportPhotos.

### PR DESCRIPTION
**Pull request by holesond**
Loading photos using relative paths (RelPath) in PhotoWindow did not work in plugin version 3.0.5 (and the latest master branch). It crashed with the following error when switching photos by clicking the left/right arrow icons or when pressing the left/right arrow keys:

```
File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/code/PhotosViewer.py", line 603, in updateWindow
              c = self.drawSelf.noImageFound()
             AttributeError: 'ImportPhotos' object has no attribute 'noImageFound'

During handling of the above exception, another exception occurred:
             
Traceback (most recent call last):
File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/code/PhotosViewer.py", line 145, in keyPressEvent
self.selfwindow.leftClickButton()
File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/code/PhotosViewer.py", line 588, in leftClickButton
self.updateWindow()
File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImportPhotos/code/PhotosViewer.py", line 606, in updateWindow
c = self.drawSelf.noImageFound()
AttributeError: 'ImportPhotos' object has no attribute 'noImageFound'
```

This pull request fixes the bug by:

- Using os.path.join instead of string concatenation to obtain the absolute image path from the project directory and RelPath.
- Assigning the QgsProject instance to drawSelf.prj in MouseClick, so that it is always available in PhotoWindow as well.

(Please note that this pull request does not attempt to address the fact that the ```drawSelf.noImageFound``` function is not defined anywhere in the codebase.)

### CODE REVIEW

**Comment by holesond** [comment]
The merge commit 2e2a3e4359da27f2fd75d7473cc702c62d444718 resolves the merge conflict by assigning the absolute path of the picture folder (instead of the relative one) to `self.selected_folder`. It also sets the photo `rel_path` in `get_geo_infos_from_photo` relatively to the QGIS project root. QGIS assumes relative paths are relative to the project root (file), not to vector layers. See e.g. https://docs.qgis.org/3.34/en/docs/user_manual/introduction/qgis_configuration.html#general-settings:

> Default paths: defines whether paths to files and layers used in new projects are stored as ‘Absolute’ or ‘Relative’ to the project file. This setting can be overwritten at the project level.

**Comment by Mariosmsk** [comment]
Thanks @holesond !
